/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Khoa;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class formKhoaHoc extends javax.swing.JPanel {

    private DefaultTableModel dtm;
    ArrayList<Khoa> list = null;

    /**
     * Creates new form fromSinhVien
     */
    public formKhoaHoc() {
        initComponents();
        dtm = new DefaultTableModel();
        dtm.addColumn("Mã Khoa");
        dtm.addColumn("Tên Khoa");
        dtm.addColumn("Thời Gian");
        list = new KhoaDAO().getAll();
        for (Khoa khoa : list) {
            dtm.addRow(toObjectsData(khoa));
        }
        jtbKhoa.setModel(dtm);
    }

    private void loaddata() {
        for (Khoa khoa : list) {
            dtm.addRow(toObjectsData(khoa));
        }
        jtbKhoa.setModel(dtm);
    }

    private static Object[] toObjectsData(Khoa k) {
        Object[] objectsData = {k.getMakhoa(), k.getTenkhoa(), k.getThoiGian()};
        return objectsData;
    }

    private void showAll() {
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        ArrayList<Khoa> khoas = new KhoaDAO().getAll();
        for (Khoa khoa : khoas) {
            Vector v = new Vector();
            v.add(khoa.getMakhoa());
            v.add(khoa.getTenkhoa());
            v.add(khoa.getThoiGian());
            dtm.addRow(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbKhoa = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        bttAddNew = new javax.swing.JButton();
        bttEdit = new javax.swing.JButton();
        bttRefresh = new javax.swing.JButton();
        bttDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        maKhoa = new javax.swing.JTextField();
        tenKhoa = new javax.swing.JTextField();
        thoiGian = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(887, 429));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Khóa Học");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jtbKhoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Khóa", "Tên Khóa Học", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbKhoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbKhoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbKhoa);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        bttAddNew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttAddNew.setForeground(new java.awt.Color(255, 51, 51));
        bttAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add_30px.png"))); // NOI18N
        bttAddNew.setText(" Thêm Mới");
        bttAddNew.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAddNewActionPerformed(evt);
            }
        });

        bttEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttEdit.setForeground(new java.awt.Color(0, 0, 255));
        bttEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit_file_30px.png"))); // NOI18N
        bttEdit.setText("      Sửa");
        bttEdit.setEnabled(false);
        bttEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEditActionPerformed(evt);
            }
        });

        bttRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh_30px.png"))); // NOI18N
        bttRefresh.setText("   Làm Mới");
        bttRefresh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRefreshActionPerformed(evt);
            }
        });

        bttDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttDelete.setForeground(new java.awt.Color(255, 0, 51));
        bttDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete_database_30px.png"))); // NOI18N
        bttDelete.setText("      Xóa");
        bttDelete.setEnabled(false);
        bttDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bttRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttAddNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(bttAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(bttEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(bttDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(bttRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Mã Khóa Học");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Tên Khóa Học");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Thời Gian");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thoiGian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tenKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void resetForm() {
        maKhoa.setText("");
        tenKhoa.setText("");
        thoiGian.setText("");
        bttAddNew.setEnabled(true);
        bttEdit.setEnabled(false);
        bttDelete.setEnabled(false);
        maKhoa.setEnabled(true);
    }
    private void bttRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRefreshActionPerformed
        resetForm();
    }//GEN-LAST:event_bttRefreshActionPerformed

    private void jtbKhoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbKhoaMouseClicked
        maKhoa.setText(jtbKhoa.getValueAt(jtbKhoa.getSelectedRow(), 0).toString());
        tenKhoa.setText(jtbKhoa.getValueAt(jtbKhoa.getSelectedRow(), 1).toString());
        thoiGian.setText(jtbKhoa.getValueAt(jtbKhoa.getSelectedRow(), 2).toString());
        bttAddNew.setEnabled(false);
        bttEdit.setEnabled(true);
        bttDelete.setEnabled(true);
        maKhoa.setEnabled(false);
    }//GEN-LAST:event_jtbKhoaMouseClicked

    private void bttDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDeleteActionPerformed
        int b = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa dữ liệu này?", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            try {
                String makhoa = maKhoa.getText();
                new KhoaDAO().deleteKhoa(makhoa);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Không thể xóa!!");
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy khóa học!!");
            }
            while (dtm.getRowCount() > 0) {
                dtm.removeRow(0);
            }
            resetForm();
            loaddata();
            bttAddNew.setEnabled(true);
            bttEdit.setEnabled(false);
            bttDelete.setEnabled(false);
            maKhoa.setEnabled(true);
        }
    }//GEN-LAST:event_bttDeleteActionPerformed

    private void bttAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAddNewActionPerformed
        String makhoa = maKhoa.getText();
        String tenkhoa = tenKhoa.getText();
        String sdt = thoiGian.getText();
        Khoa k = new Khoa(makhoa, tenkhoa, sdt);
        ArrayList<Khoa> listCheck = new KhoaDAO().checkID(makhoa);
        if (listCheck.size() > 0) {
            JOptionPane.showMessageDialog(this, "Mã ID bị trùng", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
            maKhoa.setText("");
            maKhoa.requestFocus();
            return;
        } else if (makhoa == null || makhoa.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã khóa học trống!!", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
            maKhoa.requestFocus();
            return;
        } else if (tenkhoa == null || tenkhoa.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên khóa học trống", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
            tenKhoa.requestFocus();
            return;
        } else if (sdt == null || sdt.equals("")) {
            JOptionPane.showMessageDialog(this, "Thời gian học trống", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
            thoiGian.requestFocus();
            return;
        } else {
            Khoa insert = new KhoaDAO().addNew(k);
            if (insert != null) {
                showAll();
            }
        }
        resetForm();
    }//GEN-LAST:event_bttAddNewActionPerformed

    private void bttEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEditActionPerformed
        String makhoa = maKhoa.getText();
        String tenkhoa = tenKhoa.getText();
        String sdt = thoiGian.getText();
        Khoa k = new Khoa(makhoa, tenkhoa, sdt);
        int b = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn thay đổi thông tin về khóa học này ?", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            if (tenkhoa == null || tenkhoa.equals("")) {
                JOptionPane.showMessageDialog(this, "Tên khóa học trống", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
                tenKhoa.requestFocus();
                return;
            } else if (sdt == null || sdt.equals("")) {
                JOptionPane.showMessageDialog(this, "Thời gian học trống", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
                thoiGian.requestFocus();
                return;
            } else {
                Khoa update = new KhoaDAO().updateByID(k);
                if (update != null) {
                    showAll();
                }
            }
        }
        bttAddNew.setEnabled(true);
        bttEdit.setEnabled(false);
        bttDelete.setEnabled(false);
        maKhoa.setEnabled(true);
    }//GEN-LAST:event_bttEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAddNew;
    private javax.swing.JButton bttDelete;
    private javax.swing.JButton bttEdit;
    private javax.swing.JButton bttRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbKhoa;
    private javax.swing.JTextField maKhoa;
    private javax.swing.JTextField tenKhoa;
    private javax.swing.JTextField thoiGian;
    // End of variables declaration//GEN-END:variables
}
