/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiangVien;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class formGiangVien extends javax.swing.JPanel {

    private DefaultTableModel dtm;
    private DefaultComboBoxModel dcbm;
    ArrayList<GiangVien> listgv = null;
    public static String regexDDMMYYYY = "^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d$";

    public formGiangVien() {
        initComponents();
        dcbm = new DefaultComboBoxModel();
        dtm = new DefaultTableModel();

        dtm.addColumn("ID Giáo Viên");
        dtm.addColumn("Họ Tên");
        dtm.addColumn("Ngày Sinh");
        dtm.addColumn("Giới Tính");
        dtm.addColumn("Email");
        dtm.addColumn("Địa Chỉ");
        dtm.addColumn("Số ĐT");
        loaddata();
    }

    private void loaddata() {
        listgv = new GiangVienDAO().getAll();
        for (GiangVien gv : listgv) {
            dtm.addRow(toObjectsData(gv));
        }
        jtbTTGV.setModel(dtm);
    }

    private static Object[] toObjectsData(GiangVien gv) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String date = dateFormat.format(gv.getNgaySinh());
        Object[] objectsData = {gv.getMaGV(), gv.getTenGV(), date, gv.getGioiTinh(), gv.getEmail(), gv.getDiaChi(), gv.getsDT()};
        return objectsData;
    }

    private void showAll() {
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        ArrayList<GiangVien> list = new GiangVienDAO().getAll();
        for (GiangVien gv : list) {
            Vector vector = new Vector();
            vector.add(gv.getMaGV());
            vector.add(gv.getTenGV());
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            vector.add(dateFormat.format(gv.getNgaySinh()));
            vector.add(gv.getGioiTinh());
            vector.add(gv.getEmail());
            vector.add(gv.getDiaChi());
            vector.add(gv.getsDT());
            dtm.addRow(vector);
        }
        resetForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTTGV = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        bttAddNew = new javax.swing.JButton();
        bttEdit = new javax.swing.JButton();
        bttRefresh = new javax.swing.JButton();
        bttDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        idGV = new javax.swing.JTextField();
        ngaySinh = new javax.swing.JTextField();
        diaChi = new javax.swing.JTextField();
        sDT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tenGV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        emailGV = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbGioiTinh = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(887, 429));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Giảng Viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtbTTGV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SV", "Họ Tên", "Lớp", "Khóa Học", "Ngày Sinh", "Giới Tính", "Địa Chỉ", "Số ĐT"
            }
        ));
        jtbTTGV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbTTGVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbTTGV);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        bttAddNew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttAddNew.setForeground(new java.awt.Color(255, 51, 51));
        bttAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add_30px.png"))); // NOI18N
        bttAddNew.setText(" Thêm Mới");
        bttAddNew.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAddNewActionPerformed(evt);
            }
        });

        bttEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttEdit.setForeground(new java.awt.Color(0, 0, 255));
        bttEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit_file_30px.png"))); // NOI18N
        bttEdit.setText("      Sửa");
        bttEdit.setEnabled(false);
        bttEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEditActionPerformed(evt);
            }
        });

        bttRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh_30px.png"))); // NOI18N
        bttRefresh.setText("   Làm Mới");
        bttRefresh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRefreshActionPerformed(evt);
            }
        });

        bttDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttDelete.setForeground(new java.awt.Color(255, 0, 51));
        bttDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete_database_30px.png"))); // NOI18N
        bttDelete.setText("      Xóa");
        bttDelete.setEnabled(false);
        bttDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bttRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttAddNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(bttAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(bttEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(bttDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(bttRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        jPanel3.setForeground(new java.awt.Color(0, 51, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("ID Giảng Viên");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("Họ Tên");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("Địa Chỉ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 255));
        jLabel12.setText("Số Điện Thoại");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 255));
        jLabel13.setText("Ngày Sinh");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 255));
        jLabel14.setText("Giới Tính");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 255));
        jLabel17.setText("Email");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("dd/mm/yyyy");

        jcbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel17)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idGV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailGV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jcbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sDT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idGV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(sDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailGV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14)))
                    .addComponent(jcbGioiTinh))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void resetForm() {
        idGV.setText("");
        tenGV.setText("");
        sDT.setText("");
        diaChi.setText("");
        emailGV.setText("");
        ngaySinh.setText("");
        bttAddNew.setEnabled(true);
        bttEdit.setEnabled(false);
        bttDelete.setEnabled(false);
        bttRefresh.setEnabled(true);
        idGV.setEnabled(true);
    }
    private void bttRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRefreshActionPerformed
        this.resetForm();
    }//GEN-LAST:event_bttRefreshActionPerformed

    private void bttAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAddNewActionPerformed
        String magv = idGV.getText();
        String hoten = tenGV.getText();
        String email = emailGV.getText();
        String sdt = sDT.getText();
        String ngaysinh = ngaySinh.getText();
        String gioitinh = jcbGioiTinh.getSelectedItem().toString();
        String diachi = diaChi.getText();
        Date d = null;
        if (ngaysinh == null || ngaysinh.equals("") || !ngaysinh.matches(regexDDMMYYYY)) {
            JOptionPane.showMessageDialog(this, "Nhập ngày sinh sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            ngaySinh.setText("");
            ngaySinh.requestFocus();
            return;
        } else if (magv == null || magv.equals("")) {
            JOptionPane.showMessageDialog(this, "ID Giảng viên trống!!", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            idGV.requestFocus();
            return;
        } else if (hoten == null || hoten.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên giảng viên trống!!", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            tenGV.requestFocus();
            return;
        } else if (sdt == null || sdt.equals("")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại giảng viên trống!!", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            sDT.requestFocus();
            return;
        } else if (email == null || email.equals("")) {
            JOptionPane.showMessageDialog(this, "Email giảng viên trống!!", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            emailGV.requestFocus();
            return;
        } else {
            try {
                d = new SimpleDateFormat("dd/MM/yyyy").parse(ngaysinh);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Nhập ngày sinh sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        GiangVien giangVien = new GiangVien(magv, hoten, d, gioitinh, email, diachi, sdt);
        ArrayList<GiangVien> listCheck = new GiangVienDAO().CheckID(magv);
        if (listCheck.size() > 0) {
            JOptionPane.showMessageDialog(this, "Mã ID bị trùng", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
            idGV.setText("");
            idGV.requestFocus();
            return;
        } else {
            GiangVien insert = new GiangVienDAO().addNew(giangVien);
            if (insert != null) {
                showAll();
            }
        }
    }//GEN-LAST:event_bttAddNewActionPerformed

    private void jtbTTGVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTTGVMouseClicked
        idGV.setText(jtbTTGV.getValueAt(jtbTTGV.getSelectedRow(), 0).toString());
        tenGV.setText(jtbTTGV.getValueAt(jtbTTGV.getSelectedRow(), 1).toString());
        ngaySinh.setText(jtbTTGV.getValueAt(jtbTTGV.getSelectedRow(), 2).toString());
        jcbGioiTinh.setSelectedItem(jtbTTGV.getValueAt(jtbTTGV.getSelectedRow(), 3).toString());
        emailGV.setText(jtbTTGV.getValueAt(jtbTTGV.getSelectedRow(), 4).toString());
        diaChi.setText(jtbTTGV.getValueAt(jtbTTGV.getSelectedRow(), 5).toString());
        sDT.setText(jtbTTGV.getValueAt(jtbTTGV.getSelectedRow(), 6).toString());

        bttAddNew.setEnabled(false);
        bttEdit.setEnabled(true);
        bttDelete.setEnabled(true);
        idGV.setEnabled(false);
    }//GEN-LAST:event_jtbTTGVMouseClicked

    private void bttEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEditActionPerformed
        String magv = idGV.getText();
        String hoten = tenGV.getText();
        String email = emailGV.getText();
        String sdt = sDT.getText();
        String ngaysinh = ngaySinh.getText();
        String gioitinh = jcbGioiTinh.getSelectedItem().toString();
        String diachi = diaChi.getText();
        Date d = null;
        if (ngaysinh == null || ngaysinh.equals("") || !ngaysinh.matches(regexDDMMYYYY)) {
            JOptionPane.showMessageDialog(this, "Nhập ngày sinh sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            ngaySinh.setText("");
            ngaySinh.requestFocus();
            return;
        } else if (hoten == null || hoten.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên giảng viên trống!!", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            tenGV.requestFocus();
            return;
        } else if (sdt == null || sdt.equals("")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại giảng viên trống!!", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            sDT.requestFocus();
            return;
        } else if (email == null || email.equals("")) {
            JOptionPane.showMessageDialog(this, "Email giảng viên trống!!", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            emailGV.requestFocus();
            return;
        } else {
            try {
                d = new SimpleDateFormat("dd/MM/yyyy").parse(ngaysinh);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Nhập ngày sinh sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        GiangVien giangVien = new GiangVien(magv, hoten, d, gioitinh, email, diachi, sdt);
        GiangVien update = new GiangVienDAO().updateByID(giangVien);
        if (update != null) {
            showAll();
        }
        bttAddNew.setEnabled(true);
        bttEdit.setEnabled(false);
        bttDelete.setEnabled(false);
        idGV.setEnabled(true);
    }//GEN-LAST:event_bttEditActionPerformed

    private void bttDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDeleteActionPerformed
        int b = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa dữ liệu này?", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            String magv = idGV.getText();
            try {
                new GiangVienDAO().deleteIDGV(magv);
            } catch (SQLException ex) {
                Logger.getLogger(formGiangVien.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(formGiangVien.class.getName()).log(Level.SEVERE, null, ex);
            }
            while (dtm.getRowCount() > 0) {
                dtm.removeRow(0);
            }
            resetForm();
            loaddata();
            bttAddNew.setEnabled(true);
            bttDelete.setEnabled(false);
            bttEdit.setEnabled(false);
        }
    }//GEN-LAST:event_bttDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAddNew;
    private javax.swing.JButton bttDelete;
    private javax.swing.JButton bttEdit;
    private javax.swing.JButton bttRefresh;
    private javax.swing.JTextField diaChi;
    private javax.swing.JTextField emailGV;
    private javax.swing.JTextField idGV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbGioiTinh;
    private javax.swing.JTable jtbTTGV;
    private javax.swing.JTextField ngaySinh;
    private javax.swing.JTextField sDT;
    private javax.swing.JTextField tenGV;
    // End of variables declaration//GEN-END:variables
}
