/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diem;

import LopHoc.*;
import MonHoc.*;
import SinhVien.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class formDiem extends javax.swing.JPanel {

    private DefaultTableModel dtmDSSV;
    private DefaultTableModel dtmDiem;
    private DefaultTableModel dtmTK;
    private DefaultComboBoxModel dcbmLop;
    private DefaultComboBoxModel dcbmMH;
    private DefaultComboBoxModel dcbmLanThi;
    ArrayList<SinhVien> listSV = null;
    ArrayList<MonHoc> listMH = null;
    ArrayList<LopHoc> listLH = null;
    ArrayList<Diem> listDiem = null;

    /**
     * Creates new form fromSinhVien
     */
    public formDiem() {
        try {
            initComponents();
            jcbMH.setEnabled(false);
            diemText.setEnabled(false);
            jcbLanThi.setEnabled(false);
            trangThai.setEnabled(false);

            dcbmLop = new DefaultComboBoxModel();
            dcbmMH = new DefaultComboBoxModel();
            dtmDSSV = new DefaultTableModel();
            dtmDiem = new DefaultTableModel();
            dcbmLanThi = new DefaultComboBoxModel();
            dtmTK = new DefaultTableModel();

            dtmDSSV.addColumn("Mã SV");
            dtmDSSV.addColumn("Tên SV");
            jtbDSSV.setModel(dtmDSSV);

            dtmDiem.addColumn("Tên Môn");
            dtmDiem.addColumn("Mã Môn");
            dtmDiem.addColumn("Lần Thi");
            dtmDiem.addColumn("Điểm");
            dtmDiem.addColumn("Trạng Thái");
            jtbDiem.setModel(dtmDiem);

            dtmTK.addColumn("Mã SV");
            dtmTK.addColumn("Tên SV");
            dtmTK.addColumn("Điểm");
            dtmTK.addColumn("Trạng Thái");
            jtbTK.setModel(dtmTK);

            dcbmLanThi.addElement("CT");
            dcbmLanThi.addElement("1");
            dcbmLanThi.addElement("2");
            dcbmLanThi.addElement("3");
            jcbLanThi.setModel(dcbmLanThi);
            //load lop hoc
            ILopHocDAO lopHocDAO = (ILopHocDAO) Class.forName("LopHoc.LopHocDAO").newInstance();
            listLH = lopHocDAO.getAll();
            for (LopHoc lopHoc : listLH) {
                dcbmLop.addElement(lopHoc.getMalop());
            }
            jcbML.setModel(dcbmLop);
            jcbLop.setModel(dcbmLop);
            //load mon hoc
            IMonHocDAO monHocDAO = (IMonHocDAO) Class.forName("MonHoc.MonHocDAO").newInstance();
            listMH = monHocDAO.getAll();
            for (MonHoc monHoc : listMH) {
                dcbmMH.addElement(monHoc.getMaMH());
            }
            jcbMH.setModel(dcbmMH);
            jcbMon.setModel(dcbmMH);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formDiem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(formDiem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(formDiem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        bttAddNew = new javax.swing.JButton();
        bttEdit = new javax.swing.JButton();
        bttRefresh = new javax.swing.JButton();
        bttDelete = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbDSSV = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jcbML = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbDiem = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jcbMH = new javax.swing.JComboBox<>();
        jcbLanThi = new javax.swing.JComboBox<>();
        diemText = new javax.swing.JTextField();
        trangThai = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcbLop = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcbMon = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTK = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(887, 429));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        jPanel10.setPreferredSize(new java.awt.Dimension(887, 429));
        jPanel10.setRequestFocusEnabled(false);
        jPanel10.setVerifyInputWhenFocusTarget(false);

        jPanel11.setBackground(new java.awt.Color(153, 204, 255));

        bttAddNew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttAddNew.setForeground(new java.awt.Color(255, 51, 51));
        bttAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add_30px.png"))); // NOI18N
        bttAddNew.setText(" Thêm Mới");
        bttAddNew.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAddNewActionPerformed(evt);
            }
        });

        bttEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttEdit.setForeground(new java.awt.Color(0, 0, 255));
        bttEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit_file_30px.png"))); // NOI18N
        bttEdit.setText("      Sửa");
        bttEdit.setEnabled(false);
        bttEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEditActionPerformed(evt);
            }
        });

        bttRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh_30px.png"))); // NOI18N
        bttRefresh.setText("   Làm Mới");
        bttRefresh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRefreshActionPerformed(evt);
            }
        });

        bttDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttDelete.setForeground(new java.awt.Color(255, 0, 51));
        bttDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete_database_30px.png"))); // NOI18N
        bttDelete.setText("      Xóa");
        bttDelete.setEnabled(false);
        bttDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bttRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttAddNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(bttAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(bttEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(bttDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(bttRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));

        jtbDSSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbDSSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDSSVMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtbDSSV);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Danh Sách Sinh Viên");

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));
        jPanel13.setForeground(new java.awt.Color(102, 102, 102));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Lớp");

        jcbML.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jcbML, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcbML, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Điểm các môn");

        jtbDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDiemMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtbDiem);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));

        jcbMH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbLanThi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        trangThai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        trangThai.setForeground(new java.awt.Color(0, 0, 255));
        trangThai.setText("Đạt / Không Đạt");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Môn Học");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Điểm");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Lần Thi");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Trạng Thái");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(diemText, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jcbMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbLanThi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(89, 89, 89))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbMH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jcbLanThi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(32, 32, 32)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diemText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(trangThai))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Nhập Điểm", jPanel8);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Chọn Lớp");

        jcbLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Chọn Môn");

        jcbMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Xem Điểm Của Một Lớp");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jcbLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jcbMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jcbMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jtbTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbTK);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Tìm Kiếm", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 887, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 429, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAddNewActionPerformed
        String diem = diemText.getText();
        int lanthi = jcbLanThi.getSelectedIndex();
        boolean trangthai = trangThai.isSelected();
        String masv = jtbDSSV.getValueAt(jtbDSSV.getSelectedRow(), 0).toString();
        String maMH = listMH.get(jcbMH.getSelectedIndex()).getMaMH();

        float diemsv = 0;
        try {
            diemsv = Float.parseFloat(diem);
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "Điểm không đúng định dạng!!", "Vui lòng Nhập lại.", JOptionPane.ERROR_MESSAGE);
            diemText.requestFocus();
            return;
        }
        if (diemsv > 20 || diemsv < 0) {
            JOptionPane.showMessageDialog(this, "Điểm phải nhập là số từ 0 - 20. Vui lòng nhập lại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Diem bd = new Diem(masv, maMH, lanthi, diemsv, trangthai);
        Diem insert = new DiemDAO().addNew(bd);
        if (insert != null) {
            showAll();
        }
    }//GEN-LAST:event_bttAddNewActionPerformed

    private void bttEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEditActionPerformed
        String diem = diemText.getText();
        int lanthi = jcbLanThi.getSelectedIndex();
        boolean trangthai = trangThai.isSelected();
        String masv = jtbDSSV.getValueAt(jtbDSSV.getSelectedRow(), 0).toString();
        String maMH = listMH.get(jcbMH.getSelectedIndex()).getMaMH();

        float diemsv = 0;
        try {
            diemsv = Float.parseFloat(diem);
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "Điểm không đúng định dạng!!", "Vui lòng Nhập lại.", JOptionPane.ERROR_MESSAGE);
            diemText.requestFocus();
            return;
        }
        if (diemsv > 20 || diemsv < 0) {
            JOptionPane.showMessageDialog(this, "Điểm phải nhập là số từ 0 - 20. Vui lòng nhập lại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            diemText.requestFocus();
            return;
        }

        Diem bd = new Diem(masv, maMH, lanthi, diemsv, trangthai);
        int b = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn sửa điểm sinh viên này?", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            Diem updateID = new DiemDAO().upDate(bd);
            if (updateID != null) {
                showAll();
            }
        }
        bttAddNew.setEnabled(true);
        bttDelete.setEnabled(false);
        bttEdit.setEnabled(false);
        jcbMH.setEnabled(true);
    }//GEN-LAST:event_bttEditActionPerformed

    private void bttRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRefreshActionPerformed
        resetForm();
    }//GEN-LAST:event_bttRefreshActionPerformed

    private void bttDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDeleteActionPerformed
        int b = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa dữ liệu này?", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            String masv = jtbDSSV.getValueAt(jtbDSSV.getSelectedRow(), 0).toString();
            String mamh = listMH.get(jcbMH.getSelectedIndex()).getMaMH();
            int lanthi = jcbLanThi.getSelectedIndex();
            try {
                new DiemDAO().delBangDiem(masv, mamh, lanthi);
            } catch (SQLException ex) {
                Logger.getLogger(formDiem.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(formDiem.class.getName()).log(Level.SEVERE, null, ex);
            }
            while (dtmDiem.getRowCount() > 0) {
                dtmDiem.removeRow(0);
            }
            resetForm();
            showAll();
        }
    }//GEN-LAST:event_bttDeleteActionPerformed

    private void jtbDSSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDSSVMouseClicked
        jcbMH.setEnabled(true);
        diemText.setEnabled(true);
        jcbLanThi.setEnabled(true);
        trangThai.setEnabled(true);
        showAll();
    }//GEN-LAST:event_jtbDSSVMouseClicked

    private void jcbMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMLActionPerformed
        try {
            while (dtmDSSV.getRowCount() > 0) {
                dtmDSSV.removeRow(0);
            }
            String maLop = jcbML.getSelectedItem().toString();
            ISinhVienDAO sinhVienDAO = (ISinhVienDAO) Class.forName("SinhVien.SinhVienDAO").newInstance();
            ArrayList<SinhVien> list = sinhVienDAO.findByIDLop(maLop);
            for (SinhVien sinhVien : list) {
                dtmDSSV.addRow(toObjectsDataSV(sinhVien));
            }
            jtbDSSV.setModel(dtmDSSV);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formDiem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(formDiem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(formDiem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcbMLActionPerformed

    private void jtbDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDiemMouseClicked
        jcbMH.setSelectedItem(jtbDiem.getValueAt(jtbDiem.getSelectedRow(), 1).toString());
        jcbLanThi.setSelectedItem(jtbDiem.getValueAt(jtbDiem.getSelectedRow(), 2).toString());
        diemText.setText(jtbDiem.getValueAt(jtbDiem.getSelectedRow(), 3).toString());
        String trangthai = jtbDiem.getValueAt(jtbDiem.getSelectedRow(), 4).toString();
        if (trangthai.equals("true")) {
            trangThai.setSelected(true);
        } else {
            trangThai.setSelected(false);
        }

        bttAddNew.setEnabled(false);
        bttDelete.setEnabled(true);
        bttEdit.setEnabled(true);
        jcbMH.setEnabled(false);
    }//GEN-LAST:event_jtbDiemMouseClicked

    private void jcbMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMonActionPerformed
        while (dtmTK.getRowCount() > 0) {
            dtmTK.removeRow(0);
        }
        String maLop = jcbLop.getSelectedItem().toString();
        String maMon = jcbMon.getSelectedItem().toString();
        ArrayList<SinhVien> sinhVien = new SinhVienDAO().findByIDLop(maLop);
        for (SinhVien sv : sinhVien) {
            Vector v = new Vector();
            v.add(sv.getMaSV());
            v.add(sv.getTenSV());
            ArrayList<Diem> bangDiem = new DiemDAO().loaddiem(sv.getMaSV(), maMon);
            for (Diem d : bangDiem) {
                v.add(d.getDiem());
                if (d.isTrangThai() == true) {
                    v.add("Đạt");
                } else {
                    v.add("Không Đạt");
                }
            }
            dtmTK.addRow(v);
        }
    }//GEN-LAST:event_jcbMonActionPerformed

    public void resetForm() {
        diemText.setText("");
        bttAddNew.setEnabled(true);
        bttEdit.setEnabled(false);
        bttDelete.setEnabled(false);
        jcbMH.setEnabled(true);
    }

    private static Object[] toObjectsDataSV(SinhVien sv) {
        Object[] objectsData = {sv.getMaSV(), sv.getTenSV()};
        return objectsData;
    }

    public void showAll() {
        while (dtmDiem.getRowCount() > 0) {
            dtmDiem.removeRow(0);
        }
        String masv = jtbDSSV.getValueAt(jtbDSSV.getSelectedRow(), 0).toString();
        ArrayList<Diem> bangDiem = new DiemDAO().findByIDSinhVien(masv);
        for (Diem bd : bangDiem) {
            Vector v = new Vector();
            ArrayList<MonHoc> monHoc = new MonHocDAO().findIDMaMH(bd.getMaMH());
            for (MonHoc monHoc1 : monHoc) {
                v.add(monHoc1.getTenMH());
            }
            v.add(bd.getMaMH());
            v.add(bd.getLanThi());
            v.add(bd.getDiem());
            if (bd.isTrangThai() == true) {
                v.add("Đạt");
            } else {
                v.add("Không Đạt");
            }
            dtmDiem.addRow(v);
        }
        resetForm();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAddNew;
    private javax.swing.JButton bttDelete;
    private javax.swing.JButton bttEdit;
    private javax.swing.JButton bttRefresh;
    private javax.swing.JTextField diemText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JComboBox<String> jcbLanThi;
    private javax.swing.JComboBox<String> jcbLop;
    private javax.swing.JComboBox<String> jcbMH;
    private javax.swing.JComboBox<String> jcbML;
    private javax.swing.JComboBox<String> jcbMon;
    private javax.swing.JTable jtbDSSV;
    private javax.swing.JTable jtbDiem;
    private javax.swing.JTable jtbTK;
    private javax.swing.JRadioButton trangThai;
    // End of variables declaration//GEN-END:variables
}
