/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LopHoc;

import Khoa.*;
import GiangVien.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class formLopHoc extends javax.swing.JPanel {

    private DefaultComboBoxModel dcbm;
    private DefaultComboBoxModel dcbmGV;
    private DefaultTableModel dtm;
    ArrayList<Khoa> allKhoa = null;
    ArrayList<LopHoc> allLop = null;
    ArrayList<GiangVien> allGV = null;

    public formLopHoc() {
        try {
            initComponents();
            dcbm = new DefaultComboBoxModel();
            dcbmGV = new DefaultComboBoxModel();
            dtm = new DefaultTableModel();
            IKhoaDAO khoaDAO = (IKhoaDAO) Class.forName("Khoa.KhoaDAO").newInstance();
            allKhoa = khoaDAO.getAll();
            for (Khoa k : allKhoa) {
                dcbm.addElement(k.getMakhoa());
            }
            jcbMaKhoa.setModel(dcbm);

            IGiangVienDAO giangVienDAO = (IGiangVienDAO) Class.forName("GiangVien.GiangVienDAO").newInstance();
            allGV = giangVienDAO.getAll();
            for (GiangVien giangVien : allGV) {
                dcbmGV.addElement(giangVien.getMaGV());
            }
            jcbMaGV.setModel(dcbmGV);

            dtm.addColumn("Mã Lớp");
            dtm.addColumn("Tên Lớp");
            dtm.addColumn("Mã Khoa");
            dtm.addColumn("Phòng Học");
            dtm.addColumn("Mã Giảng Viên");
            loaddata();
        } catch (InstantiationException ex) {
            Logger.getLogger(formLopHoc.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(formLopHoc.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formLopHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loaddata() {
        allLop = new LopHocDAO().getAll();
        for (LopHoc lh : allLop) {
            dtm.addRow(toObjectsData(lh));
        }
        jtbLopHoc.setModel(dtm);
    }

    private static Object[] toObjectsData(LopHoc lh) {
        Object[] objectsdata = {lh.getMalop(), lh.getTenlop(), lh.getMakhoa(), lh.getPhongHoc()};
        return objectsdata;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbLopHoc = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        bttAddNew = new javax.swing.JButton();
        bttEdit = new javax.swing.JButton();
        bttRefresh = new javax.swing.JButton();
        bttDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        maLop = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tenLop = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcbMaKhoa = new javax.swing.JComboBox<>();
        phongHoc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcbMaGV = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(887, 429));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lớp Học");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtbLopHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Lớp", "Tên Lớp", "Mã Khóa Học", "Khóa Học"
            }
        ));
        jtbLopHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbLopHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbLopHoc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        bttAddNew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttAddNew.setForeground(new java.awt.Color(255, 51, 51));
        bttAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add_30px.png"))); // NOI18N
        bttAddNew.setText(" Thêm Mới");
        bttAddNew.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAddNewActionPerformed(evt);
            }
        });

        bttEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttEdit.setForeground(new java.awt.Color(0, 0, 255));
        bttEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit_file_30px.png"))); // NOI18N
        bttEdit.setText("      Sửa");
        bttEdit.setEnabled(false);
        bttEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEditActionPerformed(evt);
            }
        });

        bttRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh_30px.png"))); // NOI18N
        bttRefresh.setText("   Làm Mới");
        bttRefresh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRefreshActionPerformed(evt);
            }
        });

        bttDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttDelete.setForeground(new java.awt.Color(255, 0, 51));
        bttDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete_database_30px.png"))); // NOI18N
        bttDelete.setText("      Xóa");
        bttDelete.setEnabled(false);
        bttDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bttRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttAddNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(bttAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(bttEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(bttDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(bttRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Mã Lớp");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("Tên Lớp");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 255));
        jLabel13.setText("Mã Khóa Học");

        jcbMaKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("Phòng Học");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 255));
        jLabel14.setText("Mã Giảng Viên");

        jcbMaGV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tenLop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(maLop, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbMaGV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbMaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phongHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(maLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jcbMaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(phongHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jcbMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void resetForm() {
        maLop.setText("");
        tenLop.setText("");
        phongHoc.setText("");
        bttAddNew.setEnabled(true);
        bttEdit.setEnabled(false);
        bttDelete.setEnabled(true);
        maLop.setEnabled(true);
    }

    private void bttRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRefreshActionPerformed
        this.resetForm();
    }//GEN-LAST:event_bttRefreshActionPerformed

    private void jtbLopHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbLopHocMouseClicked
        maLop.setText(jtbLopHoc.getValueAt(jtbLopHoc.getSelectedRow(), 0).toString());
        tenLop.setText(jtbLopHoc.getValueAt(jtbLopHoc.getSelectedRow(), 1).toString());
        jcbMaKhoa.setSelectedItem(jtbLopHoc.getValueAt(jtbLopHoc.getSelectedRow(), 2).toString());
        phongHoc.setText(jtbLopHoc.getValueAt(jtbLopHoc.getSelectedRow(), 3).toString());
        jcbMaGV.setSelectedItem(jtbLopHoc.getValueAt(jtbLopHoc.getSelectedRow(), 4).toString());

        bttAddNew.setEnabled(false);
        bttEdit.setEnabled(true);
        bttDelete.setEnabled(true);
        maLop.setEnabled(false);
    }//GEN-LAST:event_jtbLopHocMouseClicked

    private void bttDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDeleteActionPerformed
        int b = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa dữ liệu này?", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            try {
                String malop = maLop.getText();
                new LopHocDAO().deleteLopHoc(malop);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Không thể xóa vì trong lớp còn sinh viên!!");
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy khóa học!!");
            }
            while (dtm.getRowCount() > 0) {
                dtm.removeRow(0);
            }
            resetForm();
            loaddata();
            bttAddNew.setEnabled(true);
            bttDelete.setEnabled(false);
            bttEdit.setEnabled(false);
            bttRefresh.setEnabled(true);
        }
    }//GEN-LAST:event_bttDeleteActionPerformed

    private void bttAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAddNewActionPerformed
        String malop = maLop.getText();
        String tenlop = tenLop.getText();
        String makhoa = allKhoa.get(jcbMaKhoa.getSelectedIndex()).getMakhoa();
        String phonghoc = phongHoc.getText();
        String magv = allGV.get(jcbMaGV.getSelectedIndex()).getMaGV();
        LopHoc lh = new LopHoc(malop, tenlop, magv, makhoa, phonghoc);
        ArrayList<LopHoc> listCheck = new LopHocDAO().checkID(malop);
        if (listCheck.size() > 0) {
            JOptionPane.showMessageDialog(this, "Mã ID bị trùng", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
            maLop.setText("");
            maLop.requestFocus();
            return;
        } else if (malop == null || malop.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã lớp trống!!", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
            maLop.requestFocus();
            return;
        } else if (tenlop == null || tenlop.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên lớp trống!!", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
            tenLop.requestFocus();
            return;
        } else if (phonghoc == null || phonghoc.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa có phòng học!!", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
            phongHoc.requestFocus();
            return;
        } else {
            LopHoc insert = new LopHocDAO().addNew(lh);
            if (insert != null) {
                showAll();
            }
        }
    }//GEN-LAST:event_bttAddNewActionPerformed

    private void bttEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEditActionPerformed
        String malop = maLop.getText();
        String tenlop = tenLop.getText();
        String makhoa = allKhoa.get(jcbMaKhoa.getSelectedIndex()).getMakhoa();
        String phonghoc = phongHoc.getText();
        String magv = allGV.get(jcbMaGV.getSelectedIndex()).getMaGV();
        LopHoc lh = new LopHoc(malop, tenlop, magv, makhoa, phonghoc);
        int b = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn thay đổi thông tin về lớp này ?", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            if (tenlop == null || tenlop.equals("")) {
                JOptionPane.showMessageDialog(this, "Tên lớp trống!!", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
                tenLop.requestFocus();
                return;
            } else if (phonghoc == null || phonghoc.equals("")) {
                JOptionPane.showMessageDialog(this, "Chưa có phòng học!!", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
                phongHoc.requestFocus();
                return;
            } else {
                LopHoc update = new LopHocDAO().updateByID(lh);
                if (update != null) {
                    showAll();
                }
            }
        }
        bttAddNew.setEnabled(true);
        bttEdit.setEnabled(false);
        bttDelete.setEnabled(false);
        bttRefresh.setEnabled(true);
    }//GEN-LAST:event_bttEditActionPerformed

    private void showAll() {
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        int selectedIndex = jcbMaKhoa.getSelectedIndex();
//        Khoa getkhoa = allKhoa.get(selectedIndex);
        ArrayList<LopHoc> lhs = new LopHocDAO().getAll();
        for (LopHoc lopHoc : lhs) {
            Vector v = new Vector();
            v.add(lopHoc.getMalop());
            v.add(lopHoc.getTenlop());
            v.add(lopHoc.getMaGV());
            v.add(lopHoc.getMakhoa());
            v.add(lopHoc.getPhongHoc());
            dtm.addRow(v);
        }
        resetForm();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAddNew;
    private javax.swing.JButton bttDelete;
    private javax.swing.JButton bttEdit;
    private javax.swing.JButton bttRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbMaGV;
    private javax.swing.JComboBox<String> jcbMaKhoa;
    private javax.swing.JTable jtbLopHoc;
    private javax.swing.JTextField maLop;
    private javax.swing.JTextField phongHoc;
    private javax.swing.JTextField tenLop;
    // End of variables declaration//GEN-END:variables
}
